services:
  metro:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true # 인터랙티브 모드 지원 (터미널 입력 등)
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true # 윈도우 파일 시스템 감지를 위해 필요할 수 있음
